ALTER TABLE tour_images ADD COLUMN focus_x INTEGER DEFAULT 50;
ALTER TABLE tour_images ADD COLUMN focus_y INTEGER DEFAULT 50;

ALTER TABLE location_images ADD COLUMN focus_x INTEGER DEFAULT 50;
ALTER TABLE location_images ADD COLUMN focus_y INTEGER DEFAULT 50;
